server:
  port: 8080
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_db
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/create-tables.xml

twelvedata:
  api-key:
  base-url: https://api.twelvedata.com

logging:
  level:
    root: info
    com.stoliar.microservice_exchange: DEBUG